version: '3.7'

services:
  server:
    container_name: github-commit-history-server
    image: gch-server:latest
    restart: always
    build:
      context: .
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
